name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  animated_text_kit: ^4.1.1
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.3
  flutter_progress_hud: ^2.0.0
  flutter_spinkit: "^4.1.2"
  shared_preferences: ^2.0.5
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
